### ISSUE TITLE
uWS + Static

### ISSUE THREAD

**Issue by ohenepee** [dalisoft/nanoexpress#22]
How are headers added to static server and how do you combine the uWS example and the Static example without creating 2 separate servers? I've actually built an app with uWS.SSLApp and I was searching for zero-configuration NginX alternatives, which is how I arrived here thru the Web Frameworks Benchmarks.

**Comment by dalisoft** [comment]
Hi and big thanks for choosing my library. 
About 2 servers for static, i always love simplicity and performance.
If you want, you can still create two or more server instances. 

Please, can you give chunk of code which you want to use which unavailable here?

I happy to help. Every user matters for me. 

Thanks again

**Comment by dalisoft** [comment]
Hi @ohenepee 

Maybe you looking demo like [this](https://github.com/dalisoft/nanoexpress/blob/master/examples/static.js)?

**Comment by ohenepee** [comment]
Yes, but I also want to be able to use the raw `uWS` specifically the `listening_socket`... so I can gracefully stop the server

**Comment by dalisoft** [comment]
Maybe you looking to app.close method?
https://github.com/dalisoft/nanoexpress/blob/master/src/nanoexpress.js#L130

**Comment by ohenepee** [comment]
Sweet.. thanks!

**Comment by dalisoft** [comment]
Thank you for trying and/or using nanoexpress
