### ISSUE TITLE
[typescript] Interface 'nanoexpressApp' incorrectly extends interface 'TemplatedApp'.

### ISSUE THREAD

**Issue by rushprint** [dalisoft/nanoexpress#24]
HI, 

I met a error while testing typescript project.

===========================================
node_modules/nanoexpress/nanoexpress.d.ts:166:20 - error TS2430: Interface 'nanoexpressApp' incorrectly extends interface 'TemplatedApp'.
  Types of property 'listen' are incompatible.
    Type '(port: number, host?: string | undefined) => Promise<nanoexpressApp>' is not assignable to type '{ (host: RecognizedString, port: number, cb: (listenSocket: us_listen_socket) => void): TemplatedApp; (port: number, cb: (listenSocket: any) => void): TemplatedApp; }'.
      Types of parameters 'port' and 'host' are incompatible.
        Type 'RecognizedString' is not assignable to type 'number'.
          Type 'string' is not assignable to type 'number'.

166   export interface nanoexpressApp extends AppTemplatedApp {
                       ~~~~~~~~~~~~~~


Found 1 error.
===========================================

In my humble opinion, seems uWS's TemplatedApp interface had been changed and the nanoexpress.d.ts was not updated properly.

Could you check it?

**Comment by dalisoft** [comment]
Hi and thanks for reporting, but it is known issue, if i am fix this issue, some TypeScript declaration does not work properly. 

Any help would be great.

**Comment by dalisoft** [comment]
Hi @rushprint 

Can you test nanoexpress `v0.12.15` fixes this error or still exists?

**Comment by dalisoft** [comment]
I fixed errors already, but still want Confirmation from you. 
Please, can you confirm, issue is fixed or still exists?

**Comment by dalisoft** [comment]
No answer, closing
