### ISSUE TITLE
Issues integrating with Sapper

### ISSUE THREAD

**Issue by caresx** [dalisoft/nanoexpress#25]
Hi there! First off I wanna thank you and Alex for these great projects. Performance is absolutely fantastic for a node.js server, easily beating Express 5x.

While integrating with [Sapper](https://sapper.svelte.dev/) (to perform server-side rendering) I ran into a number of issues I believe are bugs. Sapper uses an express middleware to run all the routing etc.

- `req.originalUrl` is unimplemented - https://expressjs.com/en/api.html
- req.baseUrl also appears to be unimplemented but this wasn't a problem for me, just something to look out for?
- Setting res.statusCode caused the request to hang, with error 'Text and data can only be passed by String, ArrayBuffer or TypedArray.' (this originates from uWebSockets.js) even though res.end sent a `string`. I was able to fix this temporarily with `Object.defineProperty`: `Object.defineProperty(res, 'statusCode', {
      set: val => (res.rawStatusCode = val),
    });`. `res.status` didn't work either and caused the same issue as setting `res.statusCode`. I'm not sure whether `rawStatusCode` actually does anything though. I couldn't find any good examples on setting the status code other than skimming https://github.com/dalisoft/nanoexpress/blob/master/src/proto/http/polyfill-chunks/status.js.
- Normally you're meant to do `app.use(sapper.middleware())`, but I had to do `app.any(sapper.middleware())` with `nanoexpress`, as the app.use didn't fire at all. Additionally, when using `app.any` any `app.use`s would still not fire: `app.use((req, res, next) => console.log(req, res) || next());` before the `app.any` wouldn't cause anything to log.

I also found `app.setErrorHandler` and `app.setNotFoundHandler` a bit strange. It's nice and convenient but I can imagine it throwing express veterans off, especially given that `app.use` doesn't seem to work.

I've been able to fix all of these in my application code, but it was time consuming to figure out what was going wrong. Given that these are all minor issues I figured it would be better to make a single issue. If you need any help with a test case let me know.

**Comment by dalisoft** [comment]
Hello and big thanks for report and using nanoexpress. 

I am firstly express user, then transited to fastify, so i am forgot polyfill a lot of methods and properties and i am very happy to see this library helpful to someone than me. 

I am would be happy to fix these bugs, make tests to these issues. Are you able to test when fix. 

Also, i am uses different solution for middleware than using like router for performance and better error handle reason. 
Middleware will call if any of route was defined and calling. If no one defined, you can fix this by app.any(‘*’, () => {}). Express-like solution is best, that solution performance differs by 2x on medium-scale apps and reduces hosting cost by from 2 up to 25 times depending on your application code which is huge for startup projects and even for huge applications. I hope you understand why i used different solution than express. 

About other like status or polyfill properties i will look tomorrow, today bit busy.

Thanks again

**Comment by caresx** [comment]
Yup, I will be able to test. That makes sense; it would be helpful to document it though. Thank you for your time!

**Comment by caresx** [comment]
I also just found one more issue that is particularly annoying as it doesn't appear to have a good workaround. `req.method` is set to `ANY` when using app.any(...). The d.t.s says you should use `req.getMethod()` from uWebsockets.js for this method, however trying to use this method in app.any(...) will always hang because `req` is deallocated by then (Using uWS.HttpRequest past its request handler return is forbidden (it is stack allocated).) because there is an await inbetween calling the user handler.

Sapper uses req.method to determine which module method (get, post, etc.) to call. When it's set to `ANY` all server routes fail.

I've done `req.method = "GET"` for now but this obviously won't work for post methods.

**Comment by dalisoft** [comment]
Hi @caresx 

Please, can you test, issue is fixed in `v0.12.15` or still available?

**Comment by dalisoft** [comment]
@caresx 
I am also added `status` change [example](https://github.com/dalisoft/nanoexpress/blob/master/examples/status-code.js)

**Comment by caresx** [comment]
Hi! A number of issues still exist, but `req.originalUrl` is fixed now. Setting `res.statusCode` (= 200 for example) still breaks the app with the same message but `res.status` works now. `req.method` is still `ANY` for app.any routes and `req.getMethod()` still crashes inside `app.any`. The fix applied for `req.baseUrl` is also not correct and I've had to set it to '' for now. `req.baseUrl` is supposed to be used for subrouters however it's not very useful and I think always setting it to '' is fine (note that setting it to '/' caused mime errors for all my static .js files, so it really needs to be an empty string). Thanks for your time!

**Comment by dalisoft** [comment]
Hi @caresx 

Can you test now?
Also i am did polyfill which should atomically call `app.any()` even if you not define `app.any()` after using `app.use()` (can you test this functionality too?)

Thank you for your test and time :)

**Comment by caresx** [comment]
Yup, every single issue is resolved! Behaves exactly like express. Thank you very much for your time! Very excited to try out websocket support too, very promising

**Comment by dalisoft** [comment]
Thanks for report, test and help. 
Happy to see users able to use this library
