### ISSUE TITLE
http2 support

### ISSUE THREAD

**Issue by gokayokyay** [dalisoft/nanoexpress#27]
Hello!

I saw the benchmarks and it looks very promising. I'm thinking about using this library in a microservices project and I was wondering if http2 support is available. Thanks!

**Comment by dalisoft** [comment]
Hi!

Thanks for interest and i checked the library which i’ve used as core. 
https://github.com/uNetworking/uWebSockets.js
But does not find any information related http2, if uWS supports, then nanoexpress also supports. 
But i not sure about http2 support. 
I hope you understand me.

**Comment by gokayokyay** [comment]
I see, do you have any plans of implementing it? And do you plan to support SSL?

Thanks again!

**Comment by dalisoft** [comment]
Hi, sorry for late reply. 

Yea, nanoexpress supports https. 

https://github.com/dalisoft/nanoexpress/blob/38a8bec94efadeaae93d0920e9025a7dc7abd4d0/src/nanoexpress.js#L31

nanoexpress({
https: {
// ssl config here, see here https://github.com/uNetworking/uWebSockets.js/blob/master/README.md#in-a-nutshell
}
})

**Comment by dalisoft** [comment]
About http2 i not sure and i am not well know C++, so i don't think can make polyfill or something for http2 as it's implemented at Core-level

**Comment by dalisoft** [comment]
I created issue [here](https://github.com/uNetworking/uWebSockets.js/issues/178) for ask from author of uWebSockets.js as i'm used uWebSockets.js as core and it works great in most cases thanks to @alexhultman

**Comment by victor-a-rigacci** [comment]
If the concern it's performance I think http2 it's not necessary, if you add a reverse proxy like nginx it's enough to enable http2.

**Comment by dalisoft** [comment]
@victor-a-rigacci Yes, i'm mentioned it in Patreon goals

![Goals](http://joxi.ru/ZrJZzx4cMN4NZr?d=1)
