### ISSUE TITLE
Implement drop-in replacement of Express.js with 6-x performance difference?

### ISSUE THREAD

**Issue by dalisoft** [dalisoft/nanoexpress#29]
Hi users & stargazers!

I'd love to hear your ideas and agreements.
Also, for this feature (drop-in replacement), i am need two or three developer with free time and/or support for development hours (contact me for more information at dalisoft@mail.ru).

I am think this idea like `nanoexpress Pro` which is differs by performance, features and support.
If you like that, please leave "Emoji 👍".

Below you can see at which cost what you can get

Simple
- Free
- 4-5x faster than Express (not in all-cases)
- 2-3x faster than Express (for Async routes)
- Validation/Serialization out-of-the-box
- Express.Static-like method
- Auto Swagger/OpenAPI documentation
- Latest Dependencies
- Apache Licensed

Pro
- Starting from 25$/month per user (only `npm` accessing) or 50$/month (access to project private repo)
- 6-7x faster than Express (in most-cases)
- 4-5x faster than Express (for Async routes)
- Lighter size
- More polyfilled methods
- Express.Route polyfill
- Express.Static polyfill
- Less bugs and errors
- Much Stable Performance / RPS
- Auto Swagger/OpenAPI documentation
- Bug-Fixes within 4-8 hours (if you paid for **Pro**)
- Latest dependencies
- Commercial license (license will be valid until you stop paying) for closed-source project per person, ONE person can use this if purchased, other can't if other not purchased.

Note: If you not agree, i will continue support this project.
Thank you.
I hope you understand me.

Update 1: You can [try PRO](https://github.com/dalisoft/nanoexpress/tree/pro) in your open-source application
Update 2: Changing plans
Update 3: Update
Update 4: Change Commercial license term and remove support hour (who applied already until 19 August 2019 18:50:00 GMT+5, support hours will be applied for your purchased period of license)
Update 5: Typo fix
Update 6: Update
Update 7: Price improvement
Update 8: Price was changed, see my [Patreon](https://www.patreon.com/dalisoft) page

**Comment by dalisoft** [comment]
Ow, i see, you're don't want premium versions.
I'll close this issue and keep support current version

**Comment by aprilcoskun** [comment]
This library still in Alpha. I think it's too early to talking about paid versions.

**Comment by dalisoft** [comment]
@aprilcoskun You may be right, but i don't see any reason to don't make this way. I keep this project in Alpha, because there may be some bugs (tested, but not fully).
I want create 4 type of product which (2 of them already done at 50-60% locally).

Thanks for tip!

**Comment by dalisoft** [comment]
@aprilcoskun Can you try [PRO](https://github.com/dalisoft/nanoexpress/tree/pro) and leave feedback?

**Comment by dalisoft** [comment]
This issue will be closed as i'll refered [here](https://github.com/dalisoft/nanoexpress/commit/2c1cdabd1c62841602e4c5c7a0e8ebd9d42d0802)
