### ISSUE TITLE
schema validation does not work

### ISSUE THREAD

**Issue by CnApTaK** [dalisoft/nanoexpress#30]
![image](https://user-images.githubusercontent.com/1032312/63305573-0f87ac00-c2f0-11e9-967b-fcf9f6a11acc.png)

**Comment by dalisoft** [comment]
@CnApTaK Hi, please paste snippet of code as code, test again and make sure everything correct.
Thanks for reporting

**Comment by dalisoft** [comment]
Requiring `ajv`, `fast-json-stringify` and `cookie` doesn't need because of nanoexpress does it for your

**Comment by dalisoft** [comment]
@CnApTaK Please test again, is this issue was fixed or still exists?

**Comment by CnApTaK** [comment]
```javascript
const nanoexpress = require('nanoexpress');
const app = nanoexpress({
	swagger: {
		openapi: '3.0.0',
		info: {
			title: 'title',
			version: '0.0.1',
			description: 'description'
		},
		host: 'localhost:4000',
		basePath: '/'
	}
	, ajv: {
		allErrors: true,
		removeAdditional: 'all',
		useDefaults: true,
		coerceTypes: true,
		$data: true,
	}
});
app.get(
	'/',
	{
		summary: 'summary',
		description: 'description',
		contentType: 'application/json',
		schema: {
			query: {
				description: 'query desc',
				type: 'object',
				required: ['test'],
				properties: {
					test: { description: 'test', type: 'string' }
				},
			},
			response: {
				description: 'Hello world response',
				type: 'object',
				properties: {
					hello: { type: 'string' }
				}
			}
		}
	},
	async (req) => {
		console.log('query: %s', req.query);
		console.log('where is required validation error? "test" parameter is required in schema');
		return { hello: 'world' };}
);
app.get('/docs', (req, res) => {
	res.sendFile(__dirname + '/swagger-redoc.html');
});
app.listen(8080, '0.0.0.0');
```
![image](https://user-images.githubusercontent.com/1032312/63352133-2dddbe00-c369-11e9-8cb5-becea5a74d27.png)

**Comment by dalisoft** [comment]
@CnApTaK Thanks for snippet and i can confirm this works. May be you still not updated to latest version of nanoexpress?

**Comment by CnApTaK** [comment]
latest now is kinda working
for example this one
![image](https://user-images.githubusercontent.com/1032312/63353739-e3aa0c00-c36b-11e9-951d-3170498163bd.png)

but why it shows different error for this request?
![image](https://user-images.githubusercontent.com/1032312/63353820-fe7c8080-c36b-11e9-8a79-ba04c570f4a6.png)

can query by default be an object? like empty object?

**Comment by dalisoft** [comment]
@CnApTaK Maybe something wrong with your schema? I don't know, tomorrow i will try to understand why this happens. If your application isn't Closed-source, you can try PRO version, see, if that's working, then simple version has bugs, else something wrong with your schema, because i spent a lot of time to rewrite PRO version from simple version

**Comment by CnApTaK** [comment]
PRO of what? swagger? redoc?

**Comment by dalisoft** [comment]
https://github.com/dalisoft/nanoexpress/tree/pro

**Comment by CnApTaK** [comment]
ok. can you share also info about price for PRO version? cannot find it

**Comment by dalisoft** [comment]
It's here https://github.com/dalisoft/nanoexpress/issues/29

**Comment by CnApTaK** [comment]
can you help me a little bit? how to install pro version? with npm? dowloading as ZIP and unpacking doesnt work

**Comment by dalisoft** [comment]
@CnApTaK Try guide from [here](https://github.com/dalisoft/nanoexpress/blob/pro/docs/get-started.md#npm) and use only ES6 Imports, not CJS available yet for PRO

**Comment by CnApTaK** [comment]
can you check what im doing wrong here?
![image](https://user-images.githubusercontent.com/1032312/63359234-1278b000-c375-11e9-9f48-35a6ecf19085.png)
installed with: npm install dalisoft/nanoexpress#pro
same source is working when installed with: npm i nanoexpress@0.12.18

**Comment by dalisoft** [comment]
@CnApTaK Try `import nanoexpress from 'nanoexpress/src/nanoexpress.js` as Node.js still does not support ESM module good

**Comment by CnApTaK** [comment]
does not help
![image](https://user-images.githubusercontent.com/1032312/63364441-3db3cd00-c37e-11e9-983e-b05bf022f5b1.png)

**Comment by dalisoft** [comment]
There something wrong with your Node.js or may be i wrong.
But i always use Rollup (my favorite) or Webpack for to be working properly my apps.

Please, use these tools.

**Comment by CnApTaK** [comment]
i have latest stable node.js release v12.8.1
testet also on other pc with node v12.6.0
same result
somethinf wrong with your pro version
cuz master version is working and every other library im using working without any problem

**Comment by dalisoft** [comment]
`master` branch is working because of there has `CommonJS` build!!! Also i'm described it [here](https://github.com/dalisoft/nanoexpress/issues/30#issuecomment-523043382).
Try Rollup or Webpack. NodeJS does not support ES6 Imports fully and also shown log which it's in **EXPERIMENTAL**, not stable

**Comment by CnApTaK** [comment]
ok. but now cant even install it
![image](https://user-images.githubusercontent.com/1032312/63367648-fe3caf00-c384-11e9-8bbf-0c40958b31a0.png)

**Comment by dalisoft** [comment]
Then do some steps.

First, clean old `node_modules` folder

1.`npm i dalisoft/nanoexpress#pro`
2. `cd node_modules/nanoexpress`
3. `npm i`
4. `npm run build`
5. `rm -rf node_modules`

Should work.

**Comment by CnApTaK** [comment]
thank u.. finally! )

**Comment by CnApTaK** [comment]
now i have only one question.. why in docs this route information does not show that parameter "test" is required?
validation working... no problem there any more..
![image](https://user-images.githubusercontent.com/1032312/63368451-97b89080-c386-11e9-8feb-569f5cc57cfa.png)

**Comment by CnApTaK** [comment]
like this..
![image](https://user-images.githubusercontent.com/1032312/63368513-c20a4e00-c386-11e9-9e81-b90cf6cb1d3d.png)

**Comment by dalisoft** [comment]
@CnApTaK Can you please test latest version? Updated and fixed a lot of bugs

**Comment by CnApTaK** [comment]
I think this is because this attribute is not in http://localhost:8080/docs/swagger.json response
![image](https://user-images.githubusercontent.com/1032312/63372328-84a9be80-c38e-11e9-9c12-0260f12ad8e4.png)

**Comment by dalisoft** [comment]
@CnApTaK Note, **PRO** branch is licensed under **GPL-3.0**!

**Comment by dalisoft** [comment]
@CnApTaK Yes, already fixed that!

**Comment by CnApTaK** [comment]
fixed one bug, added new,
now when i remove that "required" attribute from schema i see error
![image](https://user-images.githubusercontent.com/1032312/63374751-259a7880-c393-11e9-8acc-5ab22bac97cb.png)

even if i add "default" attribute in schema its not working,,,
all this AJV stuff live coercing and reading schema defaults does not work

**Comment by dalisoft** [comment]
It's because of there no Params or Query or Body which prevents from working properly. I am added that

**Comment by dalisoft** [comment]
@CnApTaK Try now with latest commit

**Comment by CnApTaK** [comment]
to much wrong logic...
```javascript
app.get(
	'/',
	{
		schema: {
			query: {
				type: 'object',
				properties: {
					ver: {
						description: 'version',
						type: 'integer',
						exclusiveMinimum: 0,
						default: 123,
					}
				},
				required: ['ver'],
			}
		}
	},
	async req => ({ query: req.query })
);
```
![image](https://user-images.githubusercontent.com/1032312/63376811-5b416080-c397-11e9-9b38-4619ff3c24ae.png)
![image](https://user-images.githubusercontent.com/1032312/63376849-6dbb9a00-c397-11e9-8c40-cf7ad0dc2ad5.png)

```javascript
app.get(
	'/',
	{
		schema: {
			query: {
				type: 'object',
				properties: {
					ver: {
						description: 'version',
						type: 'integer',
						exclusiveMinimum: 0,
						default: 123,
					}
				},
				//required: ['ver'],
			}
		}
	},
	async req => ({ query: req.query })
);
```
![image](https://user-images.githubusercontent.com/1032312/63376891-85931e00-c397-11e9-9244-2a75eb8a875b.png)
![image](https://user-images.githubusercontent.com/1032312/63376923-9348a380-c397-11e9-8fb7-a9c71e7dd0ca.png)

**Comment by CnApTaK** [comment]
in both cases problem is with url without parameter

**Comment by dalisoft** [comment]
Sorry, i am not able to do more than that's. If you want to fix, you get premium support from me by hourly.

**Comment by CnApTaK** [comment]
even this does not help
```javascript
app.use(async (req) => {
	req.query = req.query || {};
});
``

**Comment by CnApTaK** [comment]
do you want money for testing your product and finding bugs? usually such work is paid.
OK. I realized. a product with such a developer attitude is not interesting to me.
