### ISSUE TITLE
Does this work with serverless?

### ISSUE THREAD

**Issue by tojacob** [dalisoft/nanoexpress#35]
I was wondering if I can use Nanoexpress in cloud functions of firebase or lamda of aws.

**Comment by dalisoft** [comment]
Hi. Sadly, nanoexpress does not work with serverless framework. But you can check my dev env based on Lambda API which works in any serverless environment as possible. 

https://github.com/dalisoft/lambda-api-dev-env

**Comment by tojacob** [comment]
Thanks for that!

**Comment by tojacob** [comment]
Thanks for that! :)
