### ISSUE TITLE
UnhandledPromiseRejectionWarning ??

### ISSUE THREAD

**Issue by jamilservicos** [dalisoft/nanoexpress#62]
```
const html = require('ejs').renderFile(view, Object.assign({}, opts));
res.status(200);
res.setHeader('Content-Type', 'text/html; charset=utf-8');
return res.end(Buffer.from(html, "utf-8"));
```

```
(node:8243) UnhandledPromiseRejectionWarning: Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.
(node:8243) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
```

In the tests I did, sometimes the error appears and sometimes not, but only when using setheader, and only in google chrome.
Firefox tests did not result in the error.

**Comment by dalisoft** [comment]
Hi  
Thanks for reporting issue. 

Issue happening in pro and pro-esm too or only in simple version?

Can you create reproducible repository for quicker progress of solving this issue?

**Comment by jamilservicos** [comment]
I did not perform the tests on others versions, because I liked this version more.

**Comment by dalisoft** [comment]
There 3 branches on this repository

**Comment by jamilservicos** [comment]
i'm installing via: npm install --save nanoexpress

**Comment by dalisoft** [comment]
Then it’s simple version. I’ll try to reproduce and fix issue

**Comment by jamilservicos** [comment]
I was doing some tests, and I'm suspecting the "static" module; I made an alternate routine for statistics files that returns with 404, and removed "app.static". and did not give the error.
Then I did another routine to return the file via sendFile, and the error reappeared.

**Comment by jamilservicos** [comment]
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'error' of undefined
nanoexpress.js:1754:44

```
if (!result || result.error) {
      if (config._errorHandler) {
        return config._errorHandler(result.error, req, res);
      }
....
}
```

"!result" = result undefined = undefined.error;

**Comment by jamilservicos** [comment]
I solved the problem of "UnhandledPromiseRejectionWarning" by disabling app.static, and creating a routine for it by uploading the file otherwise.
the example is very simple, just for reference.
After this change the error stopped appearing, so I believe it was being created by the "app.static" module;
```
const fs = require('fs');
const path = require('path');
const mime = require('mime-types');

assetpath = path.resolve(__dirname, 'static');
assetfile = "bundle.min.css";

const getextension = assetfile.split(".");
const contenttype = mime.contentType(getextension[(getextension.length -1)]);

return Promise.all([fs.readFileSync(path.join(assetpath, assetfile))]).then(r => {
                if((r) && (r[0])) {
                    res.status(200);
                    res.setHeader('Content-Type', contenttype);
                    return res.end(r[0]);
                }
                throw new Error("Error: read file");
            }).catch(err => {
                throw new Error(err ? err : "Error: read file");
            });
```

**Comment by dalisoft** [comment]
Try use `nanoexpress-pro` or `dalisoft/nanoexpress#pro-esm` (ESM only, Node.js 13+). If it's appearing on these branches, then i will fix only `master`, else i should fix all `branches`

**Comment by jamilservicos** [comment]
I did not test esm, but I tested pro, and also the error happened when activating "static";
so I believe you should correct the "static" module of all branches to avoid this promise error.

**Comment by dalisoft** [comment]
On `simple` version i'm didn't get any errors, but on `pro` version fixed this error. Maybe you can create reproducible gist or repo?

**Comment by dalisoft** [comment]
@jamilservicos Can you test new `pro` and simple version again?

**Comment by jamilservicos** [comment]
I'm kind of out of time, so once I have some time I'll take the test

**Comment by dalisoft** [comment]
Issue was closed due of inactivity
