### ISSUE TITLE
Incorrect installation of headers, with a large number of requests

### ISSUE THREAD

**Issue by ghost** [dalisoft/nanoexpress#63]
Hi

I noticed this thing, in load testing when using the sendFile function, the response headers are duplicated.

![Аннотация 2019-12-12 135142](https://user-images.githubusercontent.com/25064638/70706216-8f45e600-1ce6-11ea-9866-8f0bcbb2464e.png)

![Аннотация 2019-12-12 135613](https://user-images.githubusercontent.com/25064638/70706566-2e6add80-1ce7-11ea-83f0-f591ad9a068d.png)

**Comment by dalisoft** [comment]
Hi @n-lebedev 

Thanks for your reporting, please can you explain step-by-step how to reproduce this bug?

**Comment by n-lebedev** [comment]
1. I created index.html file with the content "TEST"
2. Inserted the code using the sendFile function (it is visible in my screenshot)
3. Launched load testing via autocannon (autocannon -c 1000-p 100 -d 10 http://localhost:2000)

**Comment by dalisoft** [comment]
Great, but where i can see is `headers` duplicated?

**Comment by n-lebedev** [comment]
During testing, open the page on which the load is, and through Chrome DevTools look Response Headers

**Comment by dalisoft** [comment]
I'm seen on macOS Safari + wrk for load-testing and nothing strange.

Maybe on Sunday can test with autocannon + Chrome.
Can you confirm on all versions same bug or only for `nanoexpress Pro` (no ESM)?

Thanks

**Comment by n-lebedev** [comment]
On the regular version a completely different error

(node:19672) UnhandledPromiseRejectionWarning: Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.

(node:19672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2168)

**Comment by dalisoft** [comment]
I see with `wrk` everything works good. `autocannon` even makes my notebook slower and laggy after launching, i think something wrong with `autocannon`

**Comment by n-lebedev** [comment]
Try to put a smaller number of connections (-c), and during the test, refresh the page on which the requests go, and look at the headers that return.

**Comment by dalisoft** [comment]
I checked again and again and yes, issue exists, but not in `nanoexpress`, in uWebSocket.js itself as this issue exists in `sifrr-server` which both libraries built on top of uWebSockets.js (fastest node.js server ever i've seen)

**Comment by dalisoft** [comment]
This issue may be fixed in uWebSockets.js v0.17

**Comment by dalisoft** [comment]
As browser does not use pipeline we can close this. Author of uWS tested on browsers and issue did not happen, anyway will be fixed in uWebSockets.js v0.17 which may be within next month. We can close this issue as already you can track progress of uWebSocket.js on it’s repository
